

// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.com/).
// Created by Simon Hughes (https://about.me/simon.hughes).
//
// Do not make changes directly to this file - edit the template instead.
//
// The following connection settings were used to generate this file:
//     Configuration file:     "App.config"
//     Connection String Name: "CryptoAlertsContext"
//     Connection String:      "Data Source=WIN7VM;Initial Catalog=CryptoAlerts;Integrated Security=True;Connect Timeout=15;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;MultiSubnetFailover=False"
// ------------------------------------------------------------------------------------------------
// Database Edition       : Express Edition (64-bit)
// Database Engine Edition: Express

// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CryptoAlerts
{
    using System.Linq;

    #region Unit of work

    public interface ICryptoAlertsContext : System.IDisposable
    {
        System.Data.Entity.DbSet<Alert> Alerts { get; set; } // Alerts
        System.Data.Entity.DbSet<AlertSetting> AlertSettings { get; set; } // AlertSettings
        System.Data.Entity.DbSet<CurrencyPair> CurrencyPairs { get; set; } // CurrencyPairs
        System.Data.Entity.DbSet<Exchanx> Exchanges { get; set; } // Exchanges
        System.Data.Entity.DbSet<User> Users { get; set; } // Users

        int SaveChanges();
        System.Threading.Tasks.Task<int> SaveChangesAsync();
        System.Threading.Tasks.Task<int> SaveChangesAsync(System.Threading.CancellationToken cancellationToken);
        System.Data.Entity.Infrastructure.DbChangeTracker ChangeTracker { get; }
        System.Data.Entity.Infrastructure.DbContextConfiguration Configuration { get; }
        System.Data.Entity.Database Database { get; }
        System.Data.Entity.Infrastructure.DbEntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class;
        System.Data.Entity.Infrastructure.DbEntityEntry Entry(object entity);
        System.Collections.Generic.IEnumerable<System.Data.Entity.Validation.DbEntityValidationResult> GetValidationErrors();
        System.Data.Entity.DbSet Set(System.Type entityType);
        System.Data.Entity.DbSet<TEntity> Set<TEntity>() where TEntity : class;
        string ToString();
    }

    #endregion

    #region Database context

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.35.0.0")]
    public class CryptoAlertsContext : System.Data.Entity.DbContext, ICryptoAlertsContext
    {
        public System.Data.Entity.DbSet<Alert> Alerts { get; set; } // Alerts
        public System.Data.Entity.DbSet<AlertSetting> AlertSettings { get; set; } // AlertSettings
        public System.Data.Entity.DbSet<CurrencyPair> CurrencyPairs { get; set; } // CurrencyPairs
        public System.Data.Entity.DbSet<Exchanx> Exchanges { get; set; } // Exchanges
        public System.Data.Entity.DbSet<User> Users { get; set; } // Users

        static CryptoAlertsContext()
        {
            System.Data.Entity.Database.SetInitializer<CryptoAlertsContext>(null);
        }

        public CryptoAlertsContext()
            : base("Name=CryptoAlertsContext")
        {
        }

        public CryptoAlertsContext(string connectionString)
            : base(connectionString)
        {
        }

        public CryptoAlertsContext(string connectionString, System.Data.Entity.Infrastructure.DbCompiledModel model)
            : base(connectionString, model)
        {
        }

        public CryptoAlertsContext(System.Data.Common.DbConnection existingConnection, bool contextOwnsConnection)
            : base(existingConnection, contextOwnsConnection)
        {
        }

        public CryptoAlertsContext(System.Data.Common.DbConnection existingConnection, System.Data.Entity.Infrastructure.DbCompiledModel model, bool contextOwnsConnection)
            : base(existingConnection, model, contextOwnsConnection)
        {
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }

        public bool IsSqlParameterNull(System.Data.SqlClient.SqlParameter param)
        {
            var sqlValue = param.SqlValue;
            var nullableValue = sqlValue as System.Data.SqlTypes.INullable;
            if (nullableValue != null)
                return nullableValue.IsNull;
            return (sqlValue == null || sqlValue == System.DBNull.Value);
        }

        protected override void OnModelCreating(System.Data.Entity.DbModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Configurations.Add(new AlertConfiguration());
            modelBuilder.Configurations.Add(new AlertSettingConfiguration());
            modelBuilder.Configurations.Add(new CurrencyPairConfiguration());
            modelBuilder.Configurations.Add(new ExchanxConfiguration());
            modelBuilder.Configurations.Add(new UserConfiguration());
        }

        public static System.Data.Entity.DbModelBuilder CreateModel(System.Data.Entity.DbModelBuilder modelBuilder, string schema)
        {
            modelBuilder.Configurations.Add(new AlertConfiguration(schema));
            modelBuilder.Configurations.Add(new AlertSettingConfiguration(schema));
            modelBuilder.Configurations.Add(new CurrencyPairConfiguration(schema));
            modelBuilder.Configurations.Add(new ExchanxConfiguration(schema));
            modelBuilder.Configurations.Add(new UserConfiguration(schema));
            return modelBuilder;
        }
    }
    #endregion

    #region Database context factory

    public class CryptoAlertsContextFactory : System.Data.Entity.Infrastructure.IDbContextFactory<CryptoAlertsContext>
    {
        public CryptoAlertsContext Create()
        {
            return new CryptoAlertsContext();
        }
    }

    #endregion

    #region Fake Database context

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.35.0.0")]
    public class FakeCryptoAlertsContext : ICryptoAlertsContext
    {
        public System.Data.Entity.DbSet<Alert> Alerts { get; set; }
        public System.Data.Entity.DbSet<AlertSetting> AlertSettings { get; set; }
        public System.Data.Entity.DbSet<CurrencyPair> CurrencyPairs { get; set; }
        public System.Data.Entity.DbSet<Exchanx> Exchanges { get; set; }
        public System.Data.Entity.DbSet<User> Users { get; set; }

        public FakeCryptoAlertsContext()
        {
            Alerts = new FakeDbSet<Alert>("IAlertId");
            AlertSettings = new FakeDbSet<AlertSetting>("IAlertSettingId");
            CurrencyPairs = new FakeDbSet<CurrencyPair>("ICurrencyPairId");
            Exchanges = new FakeDbSet<Exchanx>("IExchangeId");
            Users = new FakeDbSet<User>("IUserId");
        }

        public int SaveChangesCount { get; private set; }
        public int SaveChanges()
        {
            ++SaveChangesCount;
            return 1;
        }

        public System.Threading.Tasks.Task<int> SaveChangesAsync()
        {
            ++SaveChangesCount;
            return System.Threading.Tasks.Task<int>.Factory.StartNew(() => 1);
        }

        public System.Threading.Tasks.Task<int> SaveChangesAsync(System.Threading.CancellationToken cancellationToken)
        {
            ++SaveChangesCount;
            return System.Threading.Tasks.Task<int>.Factory.StartNew(() => 1, cancellationToken);
        }

        protected virtual void Dispose(bool disposing)
        {
        }

        public void Dispose()
        {
            Dispose(true);
        }

        private System.Data.Entity.Infrastructure.DbChangeTracker _changeTracker;
        public System.Data.Entity.Infrastructure.DbChangeTracker ChangeTracker { get { return _changeTracker; } }
        private System.Data.Entity.Infrastructure.DbContextConfiguration _configuration;
        public System.Data.Entity.Infrastructure.DbContextConfiguration Configuration { get { return _configuration; } }
        private System.Data.Entity.Database _database;
        public System.Data.Entity.Database Database { get { return _database; } }
        public System.Data.Entity.Infrastructure.DbEntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class
        {
            throw new System.NotImplementedException();
        }
        public System.Data.Entity.Infrastructure.DbEntityEntry Entry(object entity)
        {
            throw new System.NotImplementedException();
        }
        public System.Collections.Generic.IEnumerable<System.Data.Entity.Validation.DbEntityValidationResult> GetValidationErrors()
        {
            throw new System.NotImplementedException();
        }
        public System.Data.Entity.DbSet Set(System.Type entityType)
        {
            throw new System.NotImplementedException();
        }
        public System.Data.Entity.DbSet<TEntity> Set<TEntity>() where TEntity : class
        {
            throw new System.NotImplementedException();
        }
        public override string ToString()
        {
            throw new System.NotImplementedException();
        }

    }

    // ************************************************************************
    // Fake DbSet
    // Implementing Find:
    //      The Find method is difficult to implement in a generic fashion. If
    //      you need to test code that makes use of the Find method it is
    //      easiest to create a test DbSet for each of the entity types that
    //      need to support find. You can then write logic to find that
    //      particular type of entity, as shown below:
    //      public class FakeBlogDbSet : FakeDbSet<Blog>
    //      {
    //          public override Blog Find(params object[] keyValues)
    //          {
    //              var id = (int) keyValues.Single();
    //              return this.SingleOrDefault(b => b.BlogId == id);
    //          }
    //      }
    //      Read more about it here: https://msdn.microsoft.com/en-us/data/dn314431.aspx
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.35.0.0")]
    public class FakeDbSet<TEntity> : System.Data.Entity.DbSet<TEntity>, IQueryable, System.Collections.Generic.IEnumerable<TEntity>, System.Data.Entity.Infrastructure.IDbAsyncEnumerable<TEntity> where TEntity : class
    {
        private readonly System.Reflection.PropertyInfo[] _primaryKeys;
        private readonly System.Collections.ObjectModel.ObservableCollection<TEntity> _data;
        private readonly IQueryable _query;

        public FakeDbSet()
        {
            _data = new System.Collections.ObjectModel.ObservableCollection<TEntity>();
            _query = _data.AsQueryable();
        }

        public FakeDbSet(params string[] primaryKeys)
        {
            _primaryKeys = typeof(TEntity).GetProperties().Where(x => primaryKeys.Contains(x.Name)).ToArray();
            _data = new System.Collections.ObjectModel.ObservableCollection<TEntity>();
            _query = _data.AsQueryable();
        }

        public override TEntity Find(params object[] keyValues)
        {
            if (_primaryKeys == null)
                throw new System.ArgumentException("No primary keys defined");
            if (keyValues.Length != _primaryKeys.Length)
                throw new System.ArgumentException("Incorrect number of keys passed to Find method");

            var keyQuery = this.AsQueryable();
            keyQuery = keyValues
                .Select((t, i) => i)
                .Aggregate(keyQuery,
                    (current, x) =>
                        current.Where(entity => _primaryKeys[x].GetValue(entity, null).Equals(keyValues[x])));

            return keyQuery.SingleOrDefault();
        }

        public override System.Threading.Tasks.Task<TEntity> FindAsync(System.Threading.CancellationToken cancellationToken, params object[] keyValues)
        {
            return System.Threading.Tasks.Task<TEntity>.Factory.StartNew(() => Find(keyValues), cancellationToken);
        }

        public override System.Threading.Tasks.Task<TEntity> FindAsync(params object[] keyValues)
        {
            return System.Threading.Tasks.Task<TEntity>.Factory.StartNew(() => Find(keyValues));
        }

        public override System.Collections.Generic.IEnumerable<TEntity> AddRange(System.Collections.Generic.IEnumerable<TEntity> entities)
        {
            if (entities == null) throw new System.ArgumentNullException("entities");
            var items = entities.ToList();
            foreach (var entity in items)
            {
                _data.Add(entity);
            }
            return items;
        }

        public override TEntity Add(TEntity item)
        {
            if (item == null) throw new System.ArgumentNullException("item");
            _data.Add(item);
            return item;
        }

        public override System.Collections.Generic.IEnumerable<TEntity> RemoveRange(System.Collections.Generic.IEnumerable<TEntity> entities)
        {
            if (entities == null) throw new System.ArgumentNullException("entities");
            var items = entities.ToList();
            foreach (var entity in items)
            {
                _data.Remove(entity);
            }
            return items;
        }

        public override TEntity Remove(TEntity item)
        {
            if (item == null) throw new System.ArgumentNullException("item");
            _data.Remove(item);
            return item;
        }

        public override TEntity Attach(TEntity item)
        {
            if (item == null) throw new System.ArgumentNullException("item");
            _data.Add(item);
            return item;
        }

        public override TEntity Create()
        {
            return System.Activator.CreateInstance<TEntity>();
        }

        public override TDerivedEntity Create<TDerivedEntity>()
        {
            return System.Activator.CreateInstance<TDerivedEntity>();
        }

        public override System.Collections.ObjectModel.ObservableCollection<TEntity> Local
        {
            get { return _data; }
        }

        System.Type IQueryable.ElementType
        {
            get { return _query.ElementType; }
        }

        System.Linq.Expressions.Expression IQueryable.Expression
        {
            get { return _query.Expression; }
        }

        IQueryProvider IQueryable.Provider
        {
            get { return new FakeDbAsyncQueryProvider<TEntity>(_query.Provider); }
        }

        System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator()
        {
            return _data.GetEnumerator();
        }

        System.Collections.Generic.IEnumerator<TEntity> System.Collections.Generic.IEnumerable<TEntity>.GetEnumerator()
        {
            return _data.GetEnumerator();
        }

        System.Data.Entity.Infrastructure.IDbAsyncEnumerator<TEntity> System.Data.Entity.Infrastructure.IDbAsyncEnumerable<TEntity>.GetAsyncEnumerator()
        {
            return new FakeDbAsyncEnumerator<TEntity>(_data.GetEnumerator());
        }
    }

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.35.0.0")]
    public class FakeDbAsyncQueryProvider<TEntity> : System.Data.Entity.Infrastructure.IDbAsyncQueryProvider
    {
        private readonly IQueryProvider _inner;

        public FakeDbAsyncQueryProvider(IQueryProvider inner)
        {
            _inner = inner;
        }

        public IQueryable CreateQuery(System.Linq.Expressions.Expression expression)
        {
            return new FakeDbAsyncEnumerable<TEntity>(expression);
        }

        public IQueryable<TElement> CreateQuery<TElement>(System.Linq.Expressions.Expression expression)
        {
            return new FakeDbAsyncEnumerable<TElement>(expression);
        }

        public object Execute(System.Linq.Expressions.Expression expression)
        {
            return _inner.Execute(expression);
        }

        public TResult Execute<TResult>(System.Linq.Expressions.Expression expression)
        {
            return _inner.Execute<TResult>(expression);
        }

        public System.Threading.Tasks.Task<object> ExecuteAsync(System.Linq.Expressions.Expression expression, System.Threading.CancellationToken cancellationToken)
        {
            return System.Threading.Tasks.Task.FromResult(Execute(expression));
        }

        public System.Threading.Tasks.Task<TResult> ExecuteAsync<TResult>(System.Linq.Expressions.Expression expression, System.Threading.CancellationToken cancellationToken)
        {
            return System.Threading.Tasks.Task.FromResult(Execute<TResult>(expression));
        }
    }

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.35.0.0")]
    public class FakeDbAsyncEnumerable<T> : EnumerableQuery<T>, System.Data.Entity.Infrastructure.IDbAsyncEnumerable<T>, IQueryable<T>
    {
        public FakeDbAsyncEnumerable(System.Collections.Generic.IEnumerable<T> enumerable)
            : base(enumerable)
        { }

        public FakeDbAsyncEnumerable(System.Linq.Expressions.Expression expression)
            : base(expression)
        { }

        public System.Data.Entity.Infrastructure.IDbAsyncEnumerator<T> GetAsyncEnumerator()
        {
            return new FakeDbAsyncEnumerator<T>(this.AsEnumerable().GetEnumerator());
        }

        System.Data.Entity.Infrastructure.IDbAsyncEnumerator System.Data.Entity.Infrastructure.IDbAsyncEnumerable.GetAsyncEnumerator()
        {
            return GetAsyncEnumerator();
        }

        IQueryProvider IQueryable.Provider
        {
            get { return new FakeDbAsyncQueryProvider<T>(this); }
        }
    }

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.35.0.0")]
    public class FakeDbAsyncEnumerator<T> : System.Data.Entity.Infrastructure.IDbAsyncEnumerator<T>
    {
        private readonly System.Collections.Generic.IEnumerator<T> _inner;

        public FakeDbAsyncEnumerator(System.Collections.Generic.IEnumerator<T> inner)
        {
            _inner = inner;
        }

        public void Dispose()
        {
            _inner.Dispose();
        }

        public System.Threading.Tasks.Task<bool> MoveNextAsync(System.Threading.CancellationToken cancellationToken)
        {
            return System.Threading.Tasks.Task.FromResult(_inner.MoveNext());
        }

        public T Current
        {
            get { return _inner.Current; }
        }

        object System.Data.Entity.Infrastructure.IDbAsyncEnumerator.Current
        {
            get { return Current; }
        }
    }

    #endregion

    #region POCO classes

    // Alerts
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.35.0.0")]
    public class Alert
    {
        public int IAlertId { get; set; } // iAlertId (Primary key)
        public System.DateTime DtCreated { get; set; } // dtCreated
        public System.DateTime? DtSent { get; set; } // dtSent
        public System.DateTime? DtDeleted { get; set; } // dtDeleted
        public int? IUserId { get; set; } // iUserId
        public string SMessage { get; set; } // sMessage (length: 500)
        public string STitle { get; set; } // sTitle (length: 100)

        // Foreign keys

        /// <summary>
        /// Parent User pointed by [Alerts].([IUserId]) (FK_Alerts_Users)
        /// </summary>
        public virtual User User { get; set; } // FK_Alerts_Users
    }

    // AlertSettings
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.35.0.0")]
    public class AlertSetting
    {
        public int IAlertSettingId { get; set; } // iAlertSettingId (Primary key)
        public int? AlertTypeId { get; set; } // AlertTypeId
        public int? IExchangeId { get; set; } // iExchangeId
        public decimal? PriceLow { get; set; } // PriceLow
        public decimal? PriceHigh { get; set; } // PriceHigh
        public System.DateTime? DtCreated { get; set; } // dtCreated
        public System.DateTime? DtDeleted { get; set; } // dtDeleted
        public int? IUserId { get; set; } // iUserId
        public string STitle { get; set; } // sTitle (length: 100)
        public int? ICurrencyPairId { get; set; } // iCurrencyPairID

        // Foreign keys

        /// <summary>
        /// Parent CurrencyPair pointed by [AlertSettings].([ICurrencyPairId]) (FK_AlertSettings_CurrencyPairs)
        /// </summary>
        public virtual CurrencyPair CurrencyPair { get; set; } // FK_AlertSettings_CurrencyPairs

        /// <summary>
        /// Parent Exchanx pointed by [AlertSettings].([IExchangeId]) (FK_AlertSettings_Exchanges)
        /// </summary>
        public virtual Exchanx Exchanx { get; set; } // FK_AlertSettings_Exchanges

        /// <summary>
        /// Parent User pointed by [AlertSettings].([IUserId]) (FK_AlertSettings_Users)
        /// </summary>
        public virtual User User { get; set; } // FK_AlertSettings_Users
    }

    // CurrencyPairs
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.35.0.0")]
    public class CurrencyPair
    {
        public int ICurrencyPairId { get; set; } // iCurrencyPairId (Primary key)
        public string SName { get; set; } // sName (length: 50)
        public string SDescription { get; set; } // sDescription (length: 100)
        public System.DateTime DtCreated { get; set; } // dtCreated
        public System.DateTime? DtDeleted { get; set; } // dtDeleted

        // Reverse navigation

        /// <summary>
        /// Child AlertSettings where [AlertSettings].[iCurrencyPairID] point to this entity (FK_AlertSettings_CurrencyPairs)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<AlertSetting> AlertSettings { get; set; } // AlertSettings.FK_AlertSettings_CurrencyPairs

        public CurrencyPair()
        {
            DtCreated = System.DateTime.Now;
            AlertSettings = new System.Collections.Generic.List<AlertSetting>();
        }
    }

    // Exchanges
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.35.0.0")]
    public class Exchanx
    {
        public int IExchangeId { get; set; } // iExchangeId (Primary key)
        public string SName { get; set; } // sName (length: 50)
        public System.DateTime DtCreated { get; set; } // dtCreated
        public System.DateTime? DtDeleted { get; set; } // dtDeleted

        // Reverse navigation

        /// <summary>
        /// Child AlertSettings where [AlertSettings].[iExchangeId] point to this entity (FK_AlertSettings_Exchanges)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<AlertSetting> AlertSettings { get; set; } // AlertSettings.FK_AlertSettings_Exchanges

        public Exchanx()
        {
            DtCreated = System.DateTime.Now;
            AlertSettings = new System.Collections.Generic.List<AlertSetting>();
        }
    }

    // Users
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.35.0.0")]
    public class User
    {
        public int IUserId { get; set; } // iUserId (Primary key)
        public string UserName { get; set; } // UserName (length: 50)
        public string FirstName { get; set; } // FirstName (length: 50)
        public string LastName { get; set; } // LastName (length: 50)
        public System.DateTime DtCreated { get; set; } // dtCreated
        public System.DateTime? DtDeleted { get; set; } // dtDeleted

        // Reverse navigation

        /// <summary>
        /// Child Alerts where [Alerts].[iUserId] point to this entity (FK_Alerts_Users)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Alert> Alerts { get; set; } // Alerts.FK_Alerts_Users
        /// <summary>
        /// Child AlertSettings where [AlertSettings].[iUserId] point to this entity (FK_AlertSettings_Users)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<AlertSetting> AlertSettings { get; set; } // AlertSettings.FK_AlertSettings_Users

        public User()
        {
            DtCreated = System.DateTime.Now;
            AlertSettings = new System.Collections.Generic.List<AlertSetting>();
            Alerts = new System.Collections.Generic.List<Alert>();
        }
    }

    #endregion

    #region POCO Configuration

    // Alerts
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.35.0.0")]
    public class AlertConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Alert>
    {
        public AlertConfiguration()
            : this("dbo")
        {
        }

        public AlertConfiguration(string schema)
        {
            ToTable("Alerts", schema);
            HasKey(x => x.IAlertId);

            Property(x => x.IAlertId).HasColumnName(@"iAlertId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.DtCreated).HasColumnName(@"dtCreated").HasColumnType("datetime").IsRequired();
            Property(x => x.DtSent).HasColumnName(@"dtSent").HasColumnType("datetime").IsOptional();
            Property(x => x.DtDeleted).HasColumnName(@"dtDeleted").HasColumnType("datetime").IsOptional();
            Property(x => x.IUserId).HasColumnName(@"iUserId").HasColumnType("int").IsOptional();
            Property(x => x.SMessage).HasColumnName(@"sMessage").HasColumnType("nvarchar").IsOptional().HasMaxLength(500);
            Property(x => x.STitle).HasColumnName(@"sTitle").HasColumnType("nvarchar").IsOptional().HasMaxLength(100);

            // Foreign keys
            HasOptional(a => a.User).WithMany(b => b.Alerts).HasForeignKey(c => c.IUserId).WillCascadeOnDelete(false); // FK_Alerts_Users
        }
    }

    // AlertSettings
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.35.0.0")]
    public class AlertSettingConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<AlertSetting>
    {
        public AlertSettingConfiguration()
            : this("dbo")
        {
        }

        public AlertSettingConfiguration(string schema)
        {
            ToTable("AlertSettings", schema);
            HasKey(x => x.IAlertSettingId);

            Property(x => x.IAlertSettingId).HasColumnName(@"iAlertSettingId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.AlertTypeId).HasColumnName(@"AlertTypeId").HasColumnType("int").IsOptional();
            Property(x => x.IExchangeId).HasColumnName(@"iExchangeId").HasColumnType("int").IsOptional();
            Property(x => x.PriceLow).HasColumnName(@"PriceLow").HasColumnType("decimal").IsOptional().HasPrecision(18,0);
            Property(x => x.PriceHigh).HasColumnName(@"PriceHigh").HasColumnType("decimal").IsOptional().HasPrecision(18,0);
            Property(x => x.DtCreated).HasColumnName(@"dtCreated").HasColumnType("datetime").IsOptional();
            Property(x => x.DtDeleted).HasColumnName(@"dtDeleted").HasColumnType("datetime").IsOptional();
            Property(x => x.IUserId).HasColumnName(@"iUserId").HasColumnType("int").IsOptional();
            Property(x => x.STitle).HasColumnName(@"sTitle").HasColumnType("nvarchar").IsOptional().HasMaxLength(100);
            Property(x => x.ICurrencyPairId).HasColumnName(@"iCurrencyPairID").HasColumnType("int").IsOptional();

            // Foreign keys
            HasOptional(a => a.CurrencyPair).WithMany(b => b.AlertSettings).HasForeignKey(c => c.ICurrencyPairId).WillCascadeOnDelete(false); // FK_AlertSettings_CurrencyPairs
            HasOptional(a => a.Exchanx).WithMany(b => b.AlertSettings).HasForeignKey(c => c.IExchangeId).WillCascadeOnDelete(false); // FK_AlertSettings_Exchanges
            HasOptional(a => a.User).WithMany(b => b.AlertSettings).HasForeignKey(c => c.IUserId).WillCascadeOnDelete(false); // FK_AlertSettings_Users
        }
    }

    // CurrencyPairs
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.35.0.0")]
    public class CurrencyPairConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<CurrencyPair>
    {
        public CurrencyPairConfiguration()
            : this("dbo")
        {
        }

        public CurrencyPairConfiguration(string schema)
        {
            ToTable("CurrencyPairs", schema);
            HasKey(x => x.ICurrencyPairId);

            Property(x => x.ICurrencyPairId).HasColumnName(@"iCurrencyPairId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.SName).HasColumnName(@"sName").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            Property(x => x.SDescription).HasColumnName(@"sDescription").HasColumnType("nvarchar").IsOptional().HasMaxLength(100);
            Property(x => x.DtCreated).HasColumnName(@"dtCreated").HasColumnType("datetime").IsRequired();
            Property(x => x.DtDeleted).HasColumnName(@"dtDeleted").HasColumnType("datetime").IsOptional();
        }
    }

    // Exchanges
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.35.0.0")]
    public class ExchanxConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Exchanx>
    {
        public ExchanxConfiguration()
            : this("dbo")
        {
        }

        public ExchanxConfiguration(string schema)
        {
            ToTable("Exchanges", schema);
            HasKey(x => x.IExchangeId);

            Property(x => x.IExchangeId).HasColumnName(@"iExchangeId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.SName).HasColumnName(@"sName").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            Property(x => x.DtCreated).HasColumnName(@"dtCreated").HasColumnType("datetime").IsRequired();
            Property(x => x.DtDeleted).HasColumnName(@"dtDeleted").HasColumnType("datetime").IsOptional();
        }
    }

    // Users
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.35.0.0")]
    public class UserConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<User>
    {
        public UserConfiguration()
            : this("dbo")
        {
        }

        public UserConfiguration(string schema)
        {
            ToTable("Users", schema);
            HasKey(x => x.IUserId);

            Property(x => x.IUserId).HasColumnName(@"iUserId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.UserName).HasColumnName(@"UserName").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            Property(x => x.FirstName).HasColumnName(@"FirstName").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.LastName).HasColumnName(@"LastName").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.DtCreated).HasColumnName(@"dtCreated").HasColumnType("datetime").IsRequired();
            Property(x => x.DtDeleted).HasColumnName(@"dtDeleted").HasColumnType("datetime").IsOptional();
        }
    }

    #endregion

}
// </auto-generated>

